# LIMA Experiment Preprocessing Pipeline

This notebook runs the complete preprocessing pipeline for the LIMA experiment data.

## Pipeline Stages

1. **Raw Data Processing**: Convert JSON files to DataFrames
2. **Trial Data Processing**: Align effort data, calculate metrics
3. **Subjective Reports Processing**: Process anxiety/confidence ratings
4. **Mental Health Processing**: Score questionnaires (item-level and summed)
5. **Data Filtering**: Apply quality control, merge datasets
6. **Final Output**: Calculate effort metrics, create analysis-ready CSVs

## Outputs

- CSVs at every stage for transparency
- Mental health data: both item-level and summed scores
- Comprehensive logging and reports

## Setup

In [ ]:
# Imports and path configuration are handled in the Configuration cell below.

## Configuration

Set up the directories and parameters for preprocessing.

In [ ]:
from pathlib import Path
import sys

ROOT = Path('/Users/nokada/Desktop/EffortForagingUnderThreat')
sys.path.insert(0, str(ROOT / 'scripts' / 'preprocessing'))

RAW_DATA_DIR = str(ROOT / 'data' / 'exploratory_350' / 'raw')
OUTPUT_BASE_DIR = str(ROOT / 'data' / 'exploratory_350' / 'processed')

from config import PipelineConfig
from pipeline import run_full_pipeline, run_single_stage
from stage1_raw_processing import run_stage1
from stage2_trial_processing import run_stage2
from stage3_subjective_processing import run_stage3
from stage4_mental_health import run_stage4
from stage5_filtering import run_stage5

config = PipelineConfig(
    raw_data_dir=RAW_DATA_DIR,
    output_base_dir=OUTPUT_BASE_DIR,
    required_trials=81,
    press_count_threshold=89.0,
    max_trial_time=25.0,
    max_attacking_prob=0.9,
    max_calibration=9.0
)

print(f"ROOT: {ROOT}")
print(f"Raw data: {config.raw_data_dir}")
print(f"Output: {config.output_base_dir}")
print(f"Timestamp: {config.timestamp}")

## Option A: Run Full Pipeline

Run all stages in sequence with a single command.

In [3]:
# Run the complete pipeline
results = run_full_pipeline(
    raw_data_dir=RAW_DATA_DIR,
    output_base_dir=OUTPUT_BASE_DIR,
    config=config,
    stages=[1, 2, 3,4,5]  # Run all stages
)

2026-01-09 18:26:56,154 - Stage1_RawProcessing - INFO - Starting Stage 1: Raw Data Processing
2026-01-09 18:26:56,160 - Stage1_RawProcessing - INFO - Found 350 JSON files to process

============================================================
LIMA PREPROCESSING PIPELINE
Timestamp: 20260109_182654
Raw data: /Users/nokada/Documents/CALTECH/Lima-Analysis/Data/raw_data
Output: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL
============================================================

============================================================
STAGE 1: Raw Data Processing
============================================================

2026-01-09 18:26:56,937 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 66ec69d204145257feb0cd33
2026-01-09 18:27:01,654 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 66db184764f3cc95113637b9
2026-01-09 18:27:08,962 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 6747797e245cd6fcc37db13f
2026-01-09 18:27:09,769 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 62b354926116305375200028
2026-01-09 18:27:13,269 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 61307f2dc1954f2e8cf665ad
2026-01-09 18:27:13,599 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 612aad0cb69fa8ecd2f6edd8
2026-01-09 18:27:16,364 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 5b69e50eee7ae000017bd038
2026-01-09 18:27:23,450 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 673ab124dd6f6df06b143da0
2026-01-09 18:27:23,672 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 6065a8becc1f681d7a36115e
2026-01-09 18:27:26,345 - Stage1_RawProcessing - INFO - Participants not meeting 81 trials: 18
2026-01-09 18:27:26,346 - Stage1_RawProcessing - WARNING -   5fdcad62eed16d2504b27f5a: 79 trials
2026-01-09 18:27:26,346 - Stage1_RawProcessing - WARNING -   600f9342e7bc5518fa9ca92a: 54 trials
2026-01-09 18:27:26,346 - Stage1_RawProcessing - WARNING -   60fc39cce64c39328a7c8904: 71 trials
2026-01-09 18:27:26,346 - Stage1_RawProcessing - WARNING -   62e1581acad06eee3b6509dc: 77 trials
2026-01-09 18:27:26,347 - Stage1_RawProcessing - WARNING -   65be406142494ba9f82fbc07: 79 trials
2026-01-09 18:27:26,347 - Stage1_RawProcessing - WARNING -   65feaaac53eb219f09ad5ea0: 1 trials
2026-01-09 18:27:26,347 - Stage1_RawProcessing - WARNING -   6676cdb61af102d5b24e6c97: 25 trials
2026-01-09 18:27:26,348 - Stage1_RawProcessing - WARNING -   66d93919c873f5f154f0cb5d: 74 trials
2026-01-09 18:27:26,348 - Stage1_RawProcessing - WARNING -   6710e9749269c3c28298cef1: 72 trials
2026-01-09 18:27:26,348 - Stage1_RawProcessing - WARNING -   671c1da7ddd9c375e013b082: 71 trials
2026-01-09 18:27:26,349 - Stage1_RawProcessing - WARNING -   672dbc7218fe8e8e77673603: 34 trials
2026-01-09 18:27:26,349 - Stage1_RawProcessing - WARNING -   672e4d6974dacda67046dd6a: 27 trials
2026-01-09 18:27:26,349 - Stage1_RawProcessing - WARNING -   672ed17adbe86b0a33526e8b: 69 trials
2026-01-09 18:27:26,350 - Stage1_RawProcessing - WARNING -   6736f4a8fe83ffce0936bdc4: 71 trials
2026-01-09 18:27:26,350 - Stage1_RawProcessing - WARNING -   6737d2f14ae457ac63c1c66f: 80 trials
2026-01-09 18:27:26,350 - Stage1_RawProcessing - WARNING -   673b051541d4c485962acf64: 71 trials
2026-01-09 18:27:26,351 - Stage1_RawProcessing - WARNING -   674386ce67a93f7391e680d9: 53 trials
2026-01-09 18:27:26,351 - Stage1_RawProcessing - WARNING -   67449bbc907e64fce9e828a2: 79 trials
2026-01-09 18:27:26,372 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/experiment_info.csv
2026-01-09 18:27:26,374 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/experiment_info.pkl
2026-01-09 18:27:26,450 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/subjective_reports.csv
2026-01-09 18:27:26,453 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/subjective_reports.pkl
2026-01-09 18:27:26,563 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/surveys.csv
2026-01-09 18:27:26,568 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/surveys.pkl
2026-01-09 18:28:26,921 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/trial_data.csv
2026-01-09 18:28:39,775 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/trial_data.pkl
2026-01-09 18:28:40,323 - Stage1_RawProcessing - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/stage1_report.txt
2026-01-09 18:28:40,324 - Stage1_RawProcessing - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/Stage1_RawProcessing_log.txt
2026-01-09 18:28:40,324 - Stage1_RawProcessing - INFO - Stage 1 complete!
2026-01-09 18:28:42,578 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-09 18:28:42,579 - Stage2_TrialProcessing - INFO - Starting Stage 2: Trial Data Processing
2026-01-09 18:28:42,579 - Stage2_TrialProcessing - INFO - ============================================================

============================================================
STAGE 2: Trial Data Processing
============================================================

2026-01-09 18:28:46,629 - Stage2_TrialProcessing - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/trial_data.pkl
2026-01-09 18:28:46,634 - Stage2_TrialProcessing - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/experiment_info.pkl
2026-01-09 18:28:46,635 - Stage2_TrialProcessing - INFO - Loaded 26163 trial rows from 323 participants
2026-01-09 18:28:46,637 - Stage2_TrialProcessing - INFO - Found 14 participants with attackingProb > 0.9
2026-01-09 18:28:46,637 - Stage2_TrialProcessing - INFO - Saved removed participant IDs to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/participants_removed_attackingProb.txt
2026-01-09 18:28:46,649 - Stage2_TrialProcessing - INFO - Removed 14 participants, 25029 rows remaining
2026-01-09 18:28:46,666 - Stage2_TrialProcessing - INFO - Corrected attackingProb values to nearest valid level
2026-01-09 18:28:46,673 - Stage2_TrialProcessing - INFO - Renamed 'attackingProb' to 'threat'
2026-01-09 18:28:46,735 - Stage2_TrialProcessing - INFO - Merged calibration data (341 participants)
2026-01-09 18:28:46,752 - Stage2_TrialProcessing - INFO - Press count filter (threshold=89.0): kept 293, removed 16 participants
2026-01-09 18:28:46,753 - Stage2_TrialProcessing - INFO - Rows remaining: 23733
2026-01-09 18:28:46,854 - Stage2_TrialProcessing - INFO - Extracted player effort start times
2026-01-09 18:28:47,285 - Stage2_TrialProcessing - INFO - Aligned effort rates to trial windows
2026-01-09 18:28:47,613 - Stage2_TrialProcessing - INFO - Calculated windows for 293 participants
2026-01-09 18:28:47,613 - Stage2_TrialProcessing - INFO - Group window size: 0.1570s
2026-01-09 18:28:49,792 - Stage2_TrialProcessing - INFO - Calculated effort IPI and inverse latency metrics
2026-01-09 18:28:49,814 - Stage2_TrialProcessing - INFO - Calculated calibrationMax (press rate/sec): mean=6.80
2026-01-09 18:28:50,993 - Stage2_TrialProcessing - INFO - Computed binned counts and relative effort (adaptive & individual)
2026-01-09 18:28:51,748 - Stage2_TrialProcessing - INFO - Aligned predator positions
2026-01-09 18:28:53,826 - Stage2_TrialProcessing - INFO - Aligned player positions
2026-01-09 18:31:50,057 - Stage2_TrialProcessing - INFO - Calculated strike times
2026-01-09 18:31:50,147 - Stage2_TrialProcessing - INFO - Processed start distance and predator timing
2026-01-09 18:31:50,148 - Stage2_TrialProcessing - INFO - Added choice variables
2026-01-09 18:31:50,619 - Stage2_TrialProcessing - INFO - Adjusted time variables relative to effort start
2026-01-09 18:31:50,647 - Stage2_TrialProcessing - INFO - Added window info (group=0.1570)
2026-01-09 18:31:50,653 - Stage2_TrialProcessing - INFO - Computed effort_level and effort_diff
2026-01-09 18:31:50,671 - Stage2_TrialProcessing - INFO - Extracted trial numbers
2026-01-09 18:31:50,673 - Stage2_TrialProcessing - INFO - Encoded outcome (CAPTURE/FAIL=1, ESCAPE=0)
2026-01-09 18:31:50,674 - Stage2_TrialProcessing - INFO - Reconstructed effort_L and effort_H
2026-01-09 18:31:50,792 - Stage2_TrialProcessing - INFO - Computed distance_H and distance_L
2026-01-09 18:31:59,223 - Stage2_TrialProcessing - INFO - Calculated all effort metrics (mean, peak, AUC) for all phases
2026-01-09 18:31:59,224 - Stage2_TrialProcessing - INFO - ----------------------------------------
2026-01-09 18:31:59,224 - Stage2_TrialProcessing - INFO - Creating output DataFrames
2026-01-09 18:31:59,232 - Stage2_TrialProcessing - INFO - Created behavior DataFrame: 13185 rows, 293 participants
2026-01-09 18:31:59,238 - Stage2_TrialProcessing - INFO - Created behavior_rich DataFrame: 23733 rows, 34 columns
2026-01-09 18:31:59,239 - Stage2_TrialProcessing - INFO - ----------------------------------------
2026-01-09 18:31:59,239 - Stage2_TrialProcessing - INFO - Saving outputs
2026-01-09 18:31:59,274 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/behavior.csv
2026-01-09 18:31:59,276 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/behavior.pkl
2026-01-09 18:31:59,666 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/behavior_rich.csv
2026-01-09 18:31:59,671 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/behavior_rich.pkl
2026-01-09 18:32:20,838 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/processed_trials.pkl
2026-01-09 18:32:20,842 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/window_analysis.csv
2026-01-09 18:32:20,843 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/window_analysis.pkl
2026-01-09 18:32:20,846 - Stage2_TrialProcessing - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/stage2_report.txt
2026-01-09 18:32:20,847 - Stage2_TrialProcessing - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654/Stage2_TrialProcessing_log.txt
2026-01-09 18:32:20,848 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-09 18:32:20,848 - Stage2_TrialProcessing - INFO - Stage 2 complete!
2026-01-09 18:32:20,848 - Stage2_TrialProcessing - INFO - Outputs: behavior.csv, behavior_rich.csv + pickles
2026-01-09 18:32:20,848 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-09 18:32:23,327 - Stage3_SubjectiveReports - INFO - Starting Stage 3: Subjective Reports Processing
2026-01-09 18:32:23,331 - Stage3_SubjectiveReports - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/subjective_reports.pkl
2026-01-09 18:32:23,331 - Stage3_SubjectiveReports - INFO - Loaded 12102 subjective report rows
2026-01-09 18:32:23,332 - Stage3_SubjectiveReports - INFO - Rounded attackingProb to nearest 0.1
2026-01-09 18:32:23,383 - Stage3_SubjectiveReports - INFO - Calculated distanceFromSafety
2026-01-09 18:32:23,385 - Stage3_SubjectiveReports - INFO - Categorized distances
2026-01-09 18:32:23,386 - Stage3_SubjectiveReports - INFO - Added question type labels
2026-01-09 18:32:23,455 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/subjective_reports_processed.csv
2026-01-09 18:32:23,458 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/subjective_reports_processed.pkl
2026-01-09 18:32:23,470 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/anxiety_reports.csv
2026-01-09 18:32:23,472 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/anxiety_reports.pkl
2026-01-09 18:32:23,473 - Stage3_SubjectiveReports - INFO - Saved 6053 anxiety reports
2026-01-09 18:32:23,485 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/confidence_reports.csv
2026-01-09 18:32:23,486 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/confidence_reports.pkl
2026-01-09 18:32:23,487 - Stage3_SubjectiveReports - INFO - Saved 6049 confidence reports
2026-01-09 18:32:23,489 - Stage3_SubjectiveReports - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/stage3_report.txt
2026-01-09 18:32:23,489 - Stage3_SubjectiveReports - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654/Stage3_SubjectiveReports_log.txt
2026-01-09 18:32:23,490 - Stage3_SubjectiveReports - INFO - Stage 3 complete!
2026-01-09 18:32:23,491 - Stage4_MentalHealth - INFO - Starting Stage 4: Mental Health Data Processing
2026-01-09 18:32:23,496 - Stage4_MentalHealth - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654/surveys.pkl
2026-01-09 18:32:23,496 - Stage4_MentalHealth - INFO - Loaded 45333 survey responses
2026-01-09 18:32:23,498 - Stage4_MentalHealth - INFO - Available surveys: ['AMI', 'DASS21', 'MFIS', 'OASIS', 'PHQ9', 'STAI', 'STAI_2', 'STICSA']
2026-01-09 18:32:23,498 - Stage4_MentalHealth - INFO - Creating item-level DataFrames...
2026-01-09 18:32:23,502 - Stage4_MentalHealth - INFO - Created item-level data for AMI: 6084 items
2026-01-09 18:32:23,510 - Stage4_MentalHealth - INFO - Created item-level data for DASS21: 7077 items
2026-01-09 18:32:23,516 - Stage4_MentalHealth - INFO - Created item-level data for MFIS: 7035 items
2026-01-09 18:32:23,521 - Stage4_MentalHealth - INFO - Created item-level data for OASIS: 1680 items
2026-01-09 18:32:23,526 - Stage4_MentalHealth - INFO - Created item-level data for PHQ9: 3042 items

============================================================
STAGE 3: Subjective Reports Processing
============================================================

============================================================
STAGE 4: Mental Health Data Processing
============================================================

2026-01-09 18:32:23,532 - Stage4_MentalHealth - INFO - Created item-level data for STAI: 6720 items
2026-01-09 18:32:23,538 - Stage4_MentalHealth - INFO - Created item-level data for STAI_2: 6660 items
2026-01-09 18:32:23,546 - Stage4_MentalHealth - INFO - Created item-level data for STICSA: 7035 items
2026-01-09 18:32:23,687 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_items_long.csv
2026-01-09 18:32:23,691 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_items_long.pkl
2026-01-09 18:32:23,691 - Stage4_MentalHealth - INFO - Created combined item-level data (long): 45333 rows
2026-01-09 18:32:23,715 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_items_wide.csv
2026-01-09 18:32:23,716 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_items_wide.pkl
2026-01-09 18:32:23,717 - Stage4_MentalHealth - INFO - Created combined item-level data (wide): 338 participants
2026-01-09 18:32:23,740 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/AMI_items.csv
2026-01-09 18:32:23,743 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/AMI_items.pkl
2026-01-09 18:32:23,770 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/DASS21_items.csv
2026-01-09 18:32:23,771 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/DASS21_items.pkl
2026-01-09 18:32:23,799 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/MFIS_items.csv
2026-01-09 18:32:23,800 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/MFIS_items.pkl
2026-01-09 18:32:23,810 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/OASIS_items.csv
2026-01-09 18:32:23,811 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/OASIS_items.pkl
2026-01-09 18:32:23,825 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/PHQ9_items.csv
2026-01-09 18:32:23,827 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/PHQ9_items.pkl
2026-01-09 18:32:23,853 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_items.csv
2026-01-09 18:32:23,854 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_items.pkl
2026-01-09 18:32:23,879 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_2_items.csv
2026-01-09 18:32:23,881 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_2_items.pkl
2026-01-09 18:32:23,907 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STICSA_items.csv
2026-01-09 18:32:23,909 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STICSA_items.pkl
2026-01-09 18:32:23,909 - Stage4_MentalHealth - INFO - Calculating summed scores...
2026-01-09 18:32:24,173 - Stage4_MentalHealth - INFO - Calculated DASS-21 scores for 337 participants
2026-01-09 18:32:24,178 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/DASS21_scores.csv
2026-01-09 18:32:24,178 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/DASS21_scores.pkl
2026-01-09 18:32:24,424 - Stage4_MentalHealth - INFO - Calculated AMI scores for 338 participants
2026-01-09 18:32:24,429 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/AMI_scores.csv
2026-01-09 18:32:24,430 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/AMI_scores.pkl
2026-01-09 18:32:24,681 - Stage4_MentalHealth - INFO - Calculated MFIS scores for 335 participants
2026-01-09 18:32:24,685 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/MFIS_scores.csv
2026-01-09 18:32:24,686 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/MFIS_scores.pkl
2026-01-09 18:32:24,758 - Stage4_MentalHealth - INFO - Calculated OASIS scores for 336 participants
2026-01-09 18:32:24,761 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/OASIS_scores.csv
2026-01-09 18:32:24,762 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/OASIS_scores.pkl
2026-01-09 18:32:24,852 - Stage4_MentalHealth - INFO - Calculated PHQ-9 scores for 338 participants
2026-01-09 18:32:24,855 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/PHQ9_scores.csv
2026-01-09 18:32:24,856 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/PHQ9_scores.pkl
2026-01-09 18:32:25,002 - Stage4_MentalHealth - INFO - Calculated STICSA scores for 335 participants
2026-01-09 18:32:25,005 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STICSA_scores.csv
2026-01-09 18:32:25,006 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STICSA_scores.pkl
2026-01-09 18:32:25,343 - Stage4_MentalHealth - INFO - Calculated STAI scores for 337 participants
2026-01-09 18:32:25,347 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_scores.csv
2026-01-09 18:32:25,347 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/STAI_scores.pkl
2026-01-09 18:32:25,358 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_scores.csv
2026-01-09 18:32:25,360 - Stage4_MentalHealth - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/mental_health_scores.pkl
2026-01-09 18:32:25,360 - Stage4_MentalHealth - INFO - Created combined scores data: 338 participants
2026-01-09 18:32:25,370 - Stage4_MentalHealth - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/score_statistics.csv
2026-01-09 18:32:25,390 - Stage4_MentalHealth - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/stage4_report.txt
2026-01-09 18:32:25,391 - Stage4_MentalHealth - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654/Stage4_MentalHealth_log.txt
2026-01-09 18:32:25,391 - Stage4_MentalHealth - INFO - Stage 4 complete!
2026-01-09 18:32:25,393 - Stage5_Filtering - INFO - Starting Stage 5: Participant filtering & harmonization
2026-01-09 18:32:25,405 - Stage5_Filtering - INFO - Participant universe (union across inputs): 341
2026-01-09 18:32:25,419 - Stage5_Filtering - INFO - Escape-rate filter (min=0.35): keepers=293; failed=0; no_outcome=0
2026-01-09 18:32:25,420 - Stage5_Filtering - INFO - Final keepers after modality completeness: 293
2026-01-09 18:32:25,424 - Stage5_Filtering - INFO - Saved participant QC table: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/participant_qc.csv
2026-01-09 18:32:25,462 - Stage5_Filtering - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/behavior.csv
2026-01-09 18:32:25,464 - Stage5_Filtering - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/behavior.pkl

============================================================
STAGE 5: Participant Filtering & Harmonization
============================================================

2026-01-09 18:32:25,922 - Stage5_Filtering - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/behavior_rich.csv
2026-01-09 18:32:25,927 - Stage5_Filtering - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/behavior_rich.pkl
2026-01-09 18:32:25,934 - Stage5_Filtering - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/psych.csv
2026-01-09 18:32:25,935 - Stage5_Filtering - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/psych.pkl
2026-01-09 18:32:25,995 - Stage5_Filtering - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/feelings.csv
2026-01-09 18:32:25,998 - Stage5_Filtering - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/feelings.pkl
2026-01-09 18:32:25,999 - Stage5_Filtering - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/subject_mapping.csv
2026-01-09 18:32:26,000 - Stage5_Filtering - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/subject_mapping.pkl
2026-01-09 18:32:26,001 - Stage5_Filtering - INFO - Saved participant filter report: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/participant_filter_report.txt
2026-01-09 18:32:26,001 - Stage5_Filtering - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/Stage 5: Participant Filtering & Harmonization_report.txt
2026-01-09 18:32:26,001 - Stage5_Filtering - INFO - Stage 5 complete.
2026-01-09 18:32:26,002 - Stage5_Filtering - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654/Stage5_Filtering_log.txt

============================================================
PIPELINE COMPLETE
============================================================

Output Directories:
  stage1: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260109_182654
  stage2: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260109_182654
  stage3: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260109_182654
  stage4: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260109_182654
  stage5: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260109_182654

In [6]:
# Print summary of outputs
print("\n" + "="*60)
print("PIPELINE RESULTS SUMMARY")
print("="*60)

for stage_name, stage_data in results['stages'].items():
    print(f"\n{stage_name.upper()}:")
    print(f"  Output directory: {stage_data['output_dir']}")
    print(f"  Output files:")
    for output_name, output_paths in stage_data['outputs'].items():
        print(f"    - {output_name}:")
        for file_type, path in output_paths.items():
            print(f"        {file_type}: {path}")

============================================================
PIPELINE RESULTS SUMMARY
============================================================

STAGE1:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845
  Output files:
    - experiment_info:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/experiment_info.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/experiment_info.pkl
    - subjective_reports:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/subjective_reports.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/subjective_reports.pkl
    - surveys:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/surveys.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/surveys.pkl
    - trial_data:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/trial_data.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage1_raw_processing_20251219_130845/trial_data.pkl

STAGE2:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845
  Output files:
    - processed:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/processed_trials.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/processed_trials.pkl
    - windows:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/window_analysis.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/window_analysis.pkl
    - summary:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/trial_summary.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage2_trial_processing_20251219_130845/trial_summary.pkl

STAGE3:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845
  Output files:
    - processed:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/subjective_reports_processed.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/subjective_reports_processed.pkl
    - anxiety:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/anxiety_reports.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/anxiety_reports.pkl
    - confidence:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/confidence_reports.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/confidence_reports.pkl
    - summary:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/response_summary.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage3_subjective_reports_20251219_130845/response_summary.pkl

STAGE4:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845
  Output files:
    - items_long:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_items_long.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_items_long.pkl
    - items_wide:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_items_wide.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_items_wide.pkl
    - scores:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_scores.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage4_mental_health_20251219_130845/mental_health_scores.pkl

STAGE5:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845
  Output files:
    - filtered:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/filtered_trial_data.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/filtered_trial_data.pkl
    - exclusions:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/excluded_participants.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/excluded_participants.pkl
    - trial_counts:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/trial_counts.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/trial_counts.pkl
    - participant_summary:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/participant_summary.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage5_filtered_data_20251219_130845/participant_summary.pkl

STAGE6:
  Output directory: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845
  Output files:
    - full:
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/final_data_full.pkl
    - csv:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/final_analysis_data.csv
    - clean:
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/final_analysis_data.pkl
    - participant_effort:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/participant_effort_summary.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/participant_effort_summary.pkl
    - summary_by_attackingProb:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_attackingProb.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_attackingProb.pkl
    - summary_by_startDistance:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_startDistance.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_startDistance.pkl
    - summary_by_choice:
        csv: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_choice.csv
        pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData/stage6_final_output_20251219_130845/effort_by_choice.pkl

## Option B: Run Stages Individually

Run each stage separately for more control and inspection.

### Stage 1: Raw Data Processing

In [3]:
# Run Stage 1: Process raw JSON files
stage1_outputs = run_stage1(
    config=config,
    raw_data_dir=RAW_DATA_DIR,
    output_dir=config.stage1_dir
)

print("\nStage 1 outputs:")
for name, paths in stage1_outputs.items():
    print(f"  {name}: {paths}")

2026-01-29 10:08:47,144 - Stage1_RawProcessing - INFO - Starting Stage 1: Raw Data Processing
2026-01-29 10:08:47,151 - Stage1_RawProcessing - INFO - Found 350 JSON files to process
2026-01-29 10:08:47,910 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 66ec69d204145257feb0cd33
2026-01-29 10:08:52,551 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 66db184764f3cc95113637b9
2026-01-29 10:08:59,894 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 6747797e245cd6fcc37db13f
2026-01-29 10:09:00,713 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 62b354926116305375200028
2026-01-29 10:09:04,271 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 61307f2dc1954f2e8cf665ad
2026-01-29 10:09:04,597 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 612aad0cb69fa8ecd2f6edd8
2026-01-29 10:09:07,279 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 5b69e50eee7ae000017bd038
2026-01-29 10:09:13,756 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 673ab124dd6f6df06b143da0
2026-01-29 10:09:14,370 - Stage1_RawProcessing - WARNING - No ExperimentInfo for participant: 6065a8becc1f681d7a36115e
2026-01-29 10:09:15,446 - Stage1_RawProcessing - INFO - Participants not meeting 81 trials: 18
2026-01-29 10:09:15,446 - Stage1_RawProcessing - WARNING -   5fdcad62eed16d2504b27f5a: 79 trials
2026-01-29 10:09:15,446 - Stage1_RawProcessing - WARNING -   600f9342e7bc5518fa9ca92a: 54 trials
2026-01-29 10:09:15,446 - Stage1_RawProcessing - WARNING -   60fc39cce64c39328a7c8904: 71 trials
2026-01-29 10:09:15,447 - Stage1_RawProcessing - WARNING -   62e1581acad06eee3b6509dc: 77 trials
2026-01-29 10:09:15,447 - Stage1_RawProcessing - WARNING -   65be406142494ba9f82fbc07: 79 trials
2026-01-29 10:09:15,447 - Stage1_RawProcessing - WARNING -   65feaaac53eb219f09ad5ea0: 1 trials
2026-01-29 10:09:15,448 - Stage1_RawProcessing - WARNING -   6676cdb61af102d5b24e6c97: 25 trials
2026-01-29 10:09:15,448 - Stage1_RawProcessing - WARNING -   66d93919c873f5f154f0cb5d: 74 trials
2026-01-29 10:09:15,448 - Stage1_RawProcessing - WARNING -   6710e9749269c3c28298cef1: 72 trials
2026-01-29 10:09:15,448 - Stage1_RawProcessing - WARNING -   671c1da7ddd9c375e013b082: 71 trials
2026-01-29 10:09:15,449 - Stage1_RawProcessing - WARNING -   672dbc7218fe8e8e77673603: 34 trials
2026-01-29 10:09:15,449 - Stage1_RawProcessing - WARNING -   672e4d6974dacda67046dd6a: 27 trials
2026-01-29 10:09:15,449 - Stage1_RawProcessing - WARNING -   672ed17adbe86b0a33526e8b: 69 trials
2026-01-29 10:09:15,450 - Stage1_RawProcessing - WARNING -   6736f4a8fe83ffce0936bdc4: 71 trials
2026-01-29 10:09:15,450 - Stage1_RawProcessing - WARNING -   6737d2f14ae457ac63c1c66f: 80 trials
2026-01-29 10:09:15,450 - Stage1_RawProcessing - WARNING -   673b051541d4c485962acf64: 71 trials
2026-01-29 10:09:15,450 - Stage1_RawProcessing - WARNING -   674386ce67a93f7391e680d9: 53 trials
2026-01-29 10:09:15,451 - Stage1_RawProcessing - WARNING -   67449bbc907e64fce9e828a2: 79 trials
2026-01-29 10:09:15,475 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/experiment_info.csv
2026-01-29 10:09:15,478 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/experiment_info.pkl
2026-01-29 10:09:15,530 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/subjective_reports.csv
2026-01-29 10:09:15,533 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/subjective_reports.pkl
2026-01-29 10:09:15,640 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/surveys.csv
2026-01-29 10:09:15,643 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/surveys.pkl
2026-01-29 10:10:15,015 - Stage1_RawProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/trial_data.csv
2026-01-29 10:10:27,369 - Stage1_RawProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/trial_data.pkl
2026-01-29 10:10:27,893 - Stage1_RawProcessing - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/stage1_report.txt
2026-01-29 10:10:27,893 - Stage1_RawProcessing - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/Stage1_RawProcessing_log.txt
2026-01-29 10:10:27,894 - Stage1_RawProcessing - INFO - Stage 1 complete!

Stage 1 outputs:
  experiment_info: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/experiment_info.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/experiment_info.pkl')}
  subjective_reports: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/subjective_reports.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/subjective_reports.pkl')}
  surveys: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/surveys.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/surveys.pkl')}
  trial_data: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/trial_data.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/trial_data.pkl')}

In [4]:
# Inspect Stage 1 outputs
import pandas as pd

# Load and preview each output
for name, paths in stage1_outputs.items():
    csv_path = paths.get('csv')
    if csv_path and Path(csv_path).exists():
        df = pd.read_csv(csv_path)
        print(f"\n{name}: {len(df)} rows, {len(df.columns)} columns")
        if 'participantID' in df.columns:
            print(f"  Unique participants: {df['participantID'].nunique()}")
        print(f"  Columns: {list(df.columns)[:10]}..." if len(df.columns) > 10 else f"  Columns: {list(df.columns)}")

experiment_info: 1348 rows, 7 columns
  Unique participants: 341
  Columns: ['condition', 'datapath', 'effortPressCount', 'effortPressLatency', 'experimentDate', 'participantID', 'experimentInfoKey']

subjective_reports: 12102 rows, 11 columns
  Unique participants: 341
  Columns: ['attackingProb', 'questionType', 'response', 'trialNumber', 'category', 'trialCookie_rewardValue', 'trialCookie_time', 'trialCookie_weight', 'trialCookie_xPos', 'trialCookie_yPos']...

surveys: 45333 rows, 6 columns
  Unique participants: 338
  Columns: ['onsetTime', 'response', 'responseTime', 'surveyName', 'itemIndex', 'participantID']

trial_data: 26163 rows, 35 columns
  Unique participants: 323
  Columns: ['trialName', 'participantID', 'attackingProb', 'attackingTime', 'cookie1PosX', 'cookie1PosY', 'cookie1RewardValue', 'cookie1Weight', 'cookie2PosX', 'cookie2PosY']...

# STAGE 2: Trial Processing:

In [5]:
# Run Stage 2: Process trial data
stage2_outputs = run_stage2_modified(
    trial_data_path=stage1_outputs['trial_data']['pickle'],
    experiment_info_path=stage1_outputs['experiment_info']['pickle'],
    output_dir=config.stage2_dir,
    config=config
)

print("\nStage 2 outputs:")
for name, paths in stage2_outputs.items():
    print(f"  {name}: {paths}")

2026-01-29 10:12:46,383 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-29 10:12:46,384 - Stage2_TrialProcessing - INFO - Starting Stage 2: Trial Data Processing
2026-01-29 10:12:46,384 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-29 10:12:51,448 - Stage2_TrialProcessing - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/trial_data.pkl
2026-01-29 10:12:51,451 - Stage2_TrialProcessing - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage1_raw_processing_20260129_100839/experiment_info.pkl
2026-01-29 10:12:51,453 - Stage2_TrialProcessing - INFO - Loaded 26163 trial rows from 323 participants
2026-01-29 10:12:51,455 - Stage2_TrialProcessing - INFO - Found 14 participants with attackingProb > 0.9
2026-01-29 10:12:51,455 - Stage2_TrialProcessing - INFO - Saved removed participant IDs to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/participants_removed_attackingProb.txt
2026-01-29 10:12:51,465 - Stage2_TrialProcessing - INFO - Removed 14 participants, 25029 rows remaining
2026-01-29 10:12:51,480 - Stage2_TrialProcessing - INFO - Corrected attackingProb values to nearest valid level
2026-01-29 10:12:51,490 - Stage2_TrialProcessing - INFO - Renamed 'attackingProb' to 'threat'
2026-01-29 10:12:51,613 - Stage2_TrialProcessing - INFO - Merged calibration data (341 participants)
2026-01-29 10:12:51,628 - Stage2_TrialProcessing - INFO - Press count filter (threshold=89.0): kept 293, removed 16 participants
2026-01-29 10:12:51,628 - Stage2_TrialProcessing - INFO - Rows remaining: 23733
2026-01-29 10:12:52,008 - Stage2_TrialProcessing - INFO - Extracted player effort start times
2026-01-29 10:12:52,408 - Stage2_TrialProcessing - INFO - Aligned effort rates to trial windows
2026-01-29 10:12:52,691 - Stage2_TrialProcessing - INFO - Calculated windows for 293 participants
2026-01-29 10:12:52,692 - Stage2_TrialProcessing - INFO - Group window size: 0.1570s
2026-01-29 10:12:54,819 - Stage2_TrialProcessing - INFO - Calculated effort IPI and inverse latency metrics
2026-01-29 10:12:54,839 - Stage2_TrialProcessing - INFO - Calculated calibrationMax (Hz, i.e. presses/sec): mean=6.80
2026-01-29 10:12:55,980 - Stage2_TrialProcessing - INFO - Computed binned counts and relative effort (adaptive & individual)
2026-01-29 10:12:56,752 - Stage2_TrialProcessing - INFO - Aligned predator positions
2026-01-29 10:12:59,292 - Stage2_TrialProcessing - INFO - Aligned player positions
2026-01-29 10:15:51,005 - Stage2_TrialProcessing - INFO - Calculated strike times
2026-01-29 10:15:51,150 - Stage2_TrialProcessing - INFO - Processed start distance and predator timing
2026-01-29 10:15:51,151 - Stage2_TrialProcessing - INFO - Added choice variables
2026-01-29 10:15:51,151 - Stage2_TrialProcessing - INFO - Preserved raw timestamp: trialCaptureTime -> trialCaptureTime_raw
2026-01-29 10:15:51,152 - Stage2_TrialProcessing - INFO - Preserved raw timestamp: trialEndTime -> trialEndTime_raw
2026-01-29 10:15:51,153 - Stage2_TrialProcessing - INFO - Preserved raw timestamp: trialEscapeTime -> trialEscapeTime_raw
2026-01-29 10:15:51,590 - Stage2_TrialProcessing - INFO - Adjusted time variables relative to effort start
2026-01-29 10:15:51,615 - Stage2_TrialProcessing - INFO - Added window info (group=0.1570)
2026-01-29 10:15:51,621 - Stage2_TrialProcessing - INFO - Computed effort_level and effort_diff
2026-01-29 10:15:51,641 - Stage2_TrialProcessing - INFO - Extracted trial numbers
2026-01-29 10:15:51,654 - Stage2_TrialProcessing - INFO - Encoded outcome (CAPTURE/FAIL=1, ESCAPE=0):
2026-01-29 10:15:51,655 - Stage2_TrialProcessing - INFO -   captured -> 1: 7287 trials
2026-01-29 10:15:51,656 - Stage2_TrialProcessing - INFO -   escaped -> 0: 14938 trials
2026-01-29 10:15:51,656 - Stage2_TrialProcessing - INFO -   free -> -1: 1508 trials
2026-01-29 10:15:51,657 - Stage2_TrialProcessing - WARNING - WARNING: Unknown trialEndState values mapped to -1: ['free']
2026-01-29 10:15:51,659 - Stage2_TrialProcessing - INFO - Reconstructed effort_L and effort_H
2026-01-29 10:15:51,780 - Stage2_TrialProcessing - INFO - Computed distance_H and distance_L
2026-01-29 10:16:00,148 - Stage2_TrialProcessing - INFO - Calculated all effort metrics (mean, peak, AUC) for all phases
2026-01-29 10:16:00,149 - Stage2_TrialProcessing - INFO - ----------------------------------------
2026-01-29 10:16:00,149 - Stage2_TrialProcessing - INFO - Creating time-series exports (parquet)
2026-01-29 10:16:02,568 - Stage2_TrialProcessing - INFO - keypress_events: 899936 rows
2026-01-29 10:16:10,608 - Stage2_TrialProcessing - INFO - effort_ts (adaptive): 1704835 rows
2026-01-29 10:16:19,318 - Stage2_TrialProcessing - INFO - effort_ts (individual): 1793559 rows
2026-01-29 10:16:51,856 - Stage2_TrialProcessing - INFO - pos_ts: 10405592 rows
2026-01-29 10:16:54,882 - Stage2_TrialProcessing - INFO - trial_events: 23733 rows
2026-01-29 10:16:55,185 - Stage2_TrialProcessing - INFO - Saved parquet: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/keypress_events.parquet (899936 rows)
2026-01-29 10:16:56,768 - Stage2_TrialProcessing - INFO - Saved parquet: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/effort_ts.parquet (3498394 rows)
2026-01-29 10:17:00,052 - Stage2_TrialProcessing - INFO - Saved parquet: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/pos_ts.parquet (10405592 rows)
2026-01-29 10:17:00,087 - Stage2_TrialProcessing - INFO - Saved parquet: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/trial_events.parquet (23733 rows)
2026-01-29 10:17:00,088 - Stage2_TrialProcessing - INFO - ----------------------------------------
2026-01-29 10:17:00,088 - Stage2_TrialProcessing - INFO - Creating output DataFrames
2026-01-29 10:17:00,097 - Stage2_TrialProcessing - INFO - Created behavior DataFrame: 13185 rows, 293 participants
2026-01-29 10:17:00,104 - Stage2_TrialProcessing - INFO - Created behavior_rich DataFrame: 23733 rows, 39 columns
2026-01-29 10:17:00,105 - Stage2_TrialProcessing - INFO - ----------------------------------------
2026-01-29 10:17:00,105 - Stage2_TrialProcessing - INFO - Saving outputs
2026-01-29 10:17:00,134 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior.csv
2026-01-29 10:17:00,136 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior.pkl
2026-01-29 10:17:00,568 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior_rich.csv
2026-01-29 10:17:00,577 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior_rich.pkl
2026-01-29 10:17:20,188 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/processed_trials.pkl
2026-01-29 10:17:20,192 - Stage2_TrialProcessing - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/window_analysis.csv
2026-01-29 10:17:20,193 - Stage2_TrialProcessing - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/window_analysis.pkl
2026-01-29 10:17:20,198 - Stage2_TrialProcessing - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/stage2_report.txt
2026-01-29 10:17:20,198 - Stage2_TrialProcessing - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/Stage2_TrialProcessing_log.txt
2026-01-29 10:17:20,199 - Stage2_TrialProcessing - INFO - ============================================================
2026-01-29 10:17:20,199 - Stage2_TrialProcessing - INFO - Stage 2 complete!
2026-01-29 10:17:20,199 - Stage2_TrialProcessing - INFO - Outputs: behavior.csv, behavior_rich.csv + pickles + time-series parquet exports
2026-01-29 10:17:20,199 - Stage2_TrialProcessing - INFO - ============================================================

Stage 2 outputs:
  time_series: {'keypress_events': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/keypress_events.parquet'), 'effort_ts': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/effort_ts.parquet'), 'pos_ts': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/pos_ts.parquet'), 'trial_events': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/trial_events.parquet')}
  behavior: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior.pkl')}
  behavior_rich: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior_rich.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/behavior_rich.pkl')}
  processed: {'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/processed_trials.pkl')}
  windows: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/window_analysis.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/TESTINGVIGOR/stage2_trial_processing_20260129_100839/window_analysis.pkl')}

### Stage 2: Trial Data Processing

In [ ]:
# Run Stage 2: Process trial data
stage2_outputs = run_stage2(
    trial_data_path=stage1_outputs['trial_data']['pickle'],
    experiment_info_path=stage1_outputs['experiment_info']['pickle'],
    output_dir=config.stage2_dir,
    config=config
)

print("\nStage 2 outputs:")
for name, paths in stage2_outputs.items():
    print(f"  {name}: {paths}")

### Stage 3: Subjective Reports Processing

In [4]:
# Run Stage 3: Process subjective reports
stage3_outputs = run_stage3(
    subjective_reports_path=stage1_outputs['subjective_reports']['pickle'],
    output_dir=config.stage3_dir,
    config=config
)

print("\nStage 3 outputs:")
for name, paths in stage3_outputs.items():
    print(f"  {name}: {paths}")

2026-01-02 09:28:20,067 - Stage3_SubjectiveReports - INFO - Starting Stage 3: Subjective Reports Processing
2026-01-02 09:28:20,076 - Stage3_SubjectiveReports - INFO - Loaded pickle file: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage1_raw_processing_20260102_092537/subjective_reports.pkl
2026-01-02 09:28:20,077 - Stage3_SubjectiveReports - INFO - Loaded 12102 subjective report rows
2026-01-02 09:28:20,079 - Stage3_SubjectiveReports - INFO - Rounded attackingProb to nearest 0.1
2026-01-02 09:28:20,139 - Stage3_SubjectiveReports - INFO - Calculated distanceFromSafety
2026-01-02 09:28:20,141 - Stage3_SubjectiveReports - INFO - Categorized distances
2026-01-02 09:28:20,142 - Stage3_SubjectiveReports - INFO - Added question type labels
2026-01-02 09:28:20,211 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/subjective_reports_processed.csv
2026-01-02 09:28:20,214 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/subjective_reports_processed.pkl
2026-01-02 09:28:20,234 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/anxiety_reports.csv
2026-01-02 09:28:20,237 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/anxiety_reports.pkl
2026-01-02 09:28:20,237 - Stage3_SubjectiveReports - INFO - Saved 6053 anxiety reports
2026-01-02 09:28:20,256 - Stage3_SubjectiveReports - INFO - Saved CSV: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/confidence_reports.csv
2026-01-02 09:28:20,258 - Stage3_SubjectiveReports - INFO - Saved pickle: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/confidence_reports.pkl
2026-01-02 09:28:20,259 - Stage3_SubjectiveReports - INFO - Saved 6049 confidence reports
2026-01-02 09:28:20,261 - Stage3_SubjectiveReports - INFO - Processing report saved: /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/stage3_report.txt
2026-01-02 09:28:20,262 - Stage3_SubjectiveReports - INFO - Log saved to /Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/Stage3_SubjectiveReports_log.txt
2026-01-02 09:28:20,262 - Stage3_SubjectiveReports - INFO - Stage 3 complete!

Stage 3 outputs:
  processed: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/subjective_reports_processed.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/subjective_reports_processed.pkl')}
  anxiety: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/anxiety_reports.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/anxiety_reports.pkl')}
  confidence: {'csv': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/confidence_reports.csv'), 'pickle': PosixPath('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage3_subjective_reports_20260102_092537/confidence_reports.pkl')}

### Stage 4: Mental Health Data Processing

This stage produces **two key outputs**:
- **Item-level data**: Individual responses for each questionnaire item
- **Summed scores**: Subscale and total scores for each questionnaire

In [ ]:
# Run Stage 4: Process mental health questionnaires
stage4_outputs = run_stage4(
    surveys_path=stage1_outputs['surveys']['pickle'],
    output_dir=config.stage4_dir,
    config=config
)

print("\nStage 4 outputs:")
for name, paths in stage4_outputs.items():
    print(f"  {name}: {paths}")

In [ ]:
# Inspect mental health outputs

# Item-level data (wide format - one row per participant)
if 'items_wide' in stage4_outputs:
    items_wide = pd.read_csv(stage4_outputs['items_wide']['csv'])
    print(f"\nItem-level data (wide format):")
    print(f"  {len(items_wide)} participants")
    print(f"  {len(items_wide.columns)} columns (individual items)")
    print(f"  Sample columns: {list(items_wide.columns)[:10]}")

# Summed scores
if 'scores' in stage4_outputs:
    scores = pd.read_csv(stage4_outputs['scores']['csv'])
    print(f"\nSummed scores:")
    print(f"  {len(scores)} participants")
    print(f"  Columns: {list(scores.columns)}")
    print(f"\n  Score statistics:")
    score_cols = [c for c in scores.columns if c != 'participantID' and not c.endswith('_RT')]
    print(scores[score_cols].describe().round(2))

### Stage 5: Data Filtering

In [ ]:
import pandas as pd
# NOTE: Update this path to the actual stage2 output from the current run.
# df = pd.read_pickle(stage2_outputs['processed']['pickle'])
# df = pd.read_pickle('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage2_trial_processing_20260102_093207/processed_trials.pkl')

In [ ]:
# Run Stage 5: Apply filters and merge datasets
stage5_outputs = run_stage5(
    trial_data_path=stage2_outputs['processed']['pickle'],
    subjective_reports_path=stage3_outputs['processed']['pickle'],
    mental_health_path=stage4_outputs['scores']['pickle'],
    output_dir=config.stage5_dir,
    config=config
)

print("\nStage 5 outputs:")
for name, paths in stage5_outputs.items():
    print(f"  {name}: {paths}")

In [ ]:
# Check exclusion summary
if 'exclusions' in stage5_outputs:
    exclusions = pd.read_csv(stage5_outputs['exclusions']['csv'])
    print(f"\nExclusion summary:")
    print(f"  Total excluded: {len(exclusions)}")
    print(f"  By timing: {exclusions['excluded_timing'].sum()}")
    print(f"  By attacking prob: {exclusions['excluded_attacking_prob'].sum()}")
    print(f"  By calibration: {exclusions['excluded_calibration'].sum()}")

### Stage 6: Prolific Demographics

In [ ]:
# NOTE: This cell requires external Prolific demographics file not included in repo.
# Update the path below when demographics data is available.
# prolific_all = pd.read_csv(ROOT / 'data' / 'exploratory_350' / 'prolific_demographics.csv')

# prolific_all = pd.read_csv('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/Data/prolific_all.csv')
# psych = pd.read_csv('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260102_104909/psych.csv')

# def norm(s):
#     return (s.astype(str)
#               .str.normalize('NFKC')
#               .str.strip()
#               .str.replace('"', '', regex=False)
#               .str.replace("'", "", regex=False)
#               .str.upper())

# prolific_all['participantID'] = norm(prolific_all['Participant id'])
# psych['participantID'] = norm(psych['participantID'])

# psych_ids = psych['participantID'].dropna().unique()

# missing_from_prolific = (
#     pd.DataFrame({'participantID': psych_ids})
#       .merge(prolific_all[['participantID']].drop_duplicates(),
#              on='participantID', how='left', indicator=True)
# )

# missing_only = missing_from_prolific.loc[missing_from_prolific['_merge']=='left_only', 'participantID']
# print(f"Missing in Prolific (count={len(missing_only)}):")
# print(missing_only.tolist())

# prolific_matched = prolific_all[prolific_all['participantID'].isin(psych_ids)].copy()
# prolific_data = prolific_matched[['participantID', 'Age', 'Sex']].reset_index(drop=True)

# psych_demographic = pd.merge(psych, prolific_data, on='participantID', how='left')

In [17]:
from pathlib import Path

out_dir = Path(OUTPUT_BASE_DIR) / "Stage6_demographics"
out_dir.mkdir(parents=True, exist_ok=True)

psych_demographic.to_csv(
    out_dir / "psych_demographic.csv",
    index=False
)

# Stage 7 
Reshape and clean the mental health data.

In [ ]:
# NOTE: This cell requires external Prolific demographics file not included in repo.
# Update the paths below when the pipeline has been run and output files are available.
# The paths below reference a previous run's output directory (ProcessingPipelineData_FINAL)
# which is not included in the repo. Re-run stages 4 and 5 first to generate these files.

# Load data
# df_raw = pd.read_csv(ROOT / 'data' / 'exploratory_350' / 'processed' / '<stage4_dir>' / 'mental_health_items_wide.csv')
# subjs = pd.read_csv(ROOT / 'data' / 'exploratory_350' / 'processed' / '<stage5_dir>' / 'subject_mapping.csv')

# df_raw = pd.read_csv('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage4_mental_health_20260102_104909/mental_health_items_wide.csv')
# subjs = pd.read_csv('/Users/nokada/Documents/CALTECH/LIMA_Analysis/Data/ProcessingPipelineData_FINAL/stage5_filtered_data_20260102_104909/subject_mapping.csv')

# df = df_raw[df_raw['participantID'].isin(subjs['participantID'])]

# print(f"Dataset shape: {df.shape}")
# print(f"Participants: {len(df)}")
# print(f"Columns: {len(df.columns)}")
# print("\nFirst few rows:")
# df.head()

In [6]:
# Identify questionnaire columns
all_cols = [col for col in df.columns if col != 'participantID']

# Parse by questionnaire
item_info = {}
for col in all_cols:
    prefix = col.rsplit('_item_', 1)[0] if '_item_' in col else None
    if prefix:
        if prefix not in item_info:
            item_info[prefix] = []
        item_info[prefix].append(col)

print("Questionnaires detected:")
for prefix, cols in item_info.items():
    print(f"  {prefix}: {len(cols)} items")

Questionnaires detected:
  AMI: 18 items
  DASS21: 21 items
  MFIS: 21 items
  OASIS: 5 items
  PHQ9: 9 items
  STAI: 20 items
  STAI_2: 20 items
  STICSA: 21 items

In [17]:
# EXCLUDE STICSA (NON-NEGOTIABLE)
# Identify STICSA columns
sticsa_cols = item_info.get('STICSA', [])

print(f"⚠️ DROPPING {len(sticsa_cols)} STICSA items from dataframe")

# Drop from dataframe
df = df.drop(columns=sticsa_cols, errors='ignore')

# Select items to include
included_prefixes = ['AMI', 'DASS21', 'MFIS', 'OASIS', 'PHQ9', 'STAI', 'STAI_2']
item_cols = []
for prefix in included_prefixes:
    if prefix in item_info:
        item_cols.extend(item_info[prefix])

print(f"\nTotal items for analysis: {len(item_cols)}")
print(f"\nItems per measure:")
for prefix in included_prefixes:
    if prefix in item_info:
        print(f"  {prefix}: {len(item_info[prefix])} items")

⚠️ DROPPING 21 STICSA items from dataframe

Total items for analysis: 114

Items per measure:
  AMI: 18 items
  DASS21: 21 items
  MFIS: 21 items
  OASIS: 5 items
  PHQ9: 9 items
  STAI: 20 items
  STAI_2: 20 items

In [18]:
# Check response ranges (should match specification)
print("Response ranges by questionnaire:")
print("=" * 50)

expected_ranges = {
    'AMI': (0, 4),
    'DASS21': (0, 3),
    'MFIS': (0, 4),
    'OASIS': (0, 4),
    'PHQ9': (0, 3),
    'STAI': (0, 3),
    'STAI_2': (0, 3)
}

for prefix in included_prefixes:
    if prefix in item_info:
        cols = item_info[prefix]
        min_val = df[cols].min().min()
        max_val = df[cols].max().max()
        expected = expected_ranges.get(prefix, 'Unknown')
        status = "✓" if (min_val, max_val) == expected else "⚠️"
        print(f"{prefix:10s}: observed ({min_val:.0f}-{max_val:.0f}), expected {expected} {status}")

Response ranges by questionnaire:
==================================================
AMI       : observed (0-4), expected (0, 4) ✓
DASS21    : observed (0-3), expected (0, 3) ✓
MFIS      : observed (0-4), expected (0, 4) ✓
OASIS     : observed (0-4), expected (0, 4) ✓
PHQ9      : observed (0-3), expected (0, 3) ✓
STAI      : observed (0-3), expected (0, 3) ✓
STAI_2    : observed (0-3), expected (0, 3) ✓

In [19]:
# Response scale maxima
SCALE_MAX = {
    'AMI': 4,
    'DASS21': 3,
    'MFIS': 4,
    'OASIS': 4,
    'PHQ9': 3,
    'STAI': 3,
    'STAI_2': 3
}

# STAI reverse items (0-indexed)
STAI_REVERSE_ITEMS = [0, 1, 4, 7, 9, 10, 14, 15, 18, 19]  # State anxiety positively-worded
STAI_2_REVERSE_ITEMS = [0, 2, 5, 6, 9, 12, 13, 15, 18]    # Trait anxiety positively-worded

# Apply reverse scoring
df_scored = df.copy()
reverse_log = []

# AMI: ALL items
ami_cols = [col for col in item_cols if col.startswith('AMI_')]
for col in ami_cols:
    df_scored[col] = SCALE_MAX['AMI'] - df_scored[col]
    reverse_log.append(col)
print(f"AMI: Reversed {len(ami_cols)} items")

# STAI State
stai_reversed = []
for idx in STAI_REVERSE_ITEMS:
    col = f'STAI_item_{idx}'
    if col in df_scored.columns:
        df_scored[col] = SCALE_MAX['STAI'] - df_scored[col]
        stai_reversed.append(col)
        reverse_log.append(col)
print(f"STAI State: Reversed {len(stai_reversed)} items")

# STAI Trait
stai2_reversed = []
for idx in STAI_2_REVERSE_ITEMS:
    col = f'STAI_2_item_{idx}'
    if col in df_scored.columns:
        df_scored[col] = SCALE_MAX['STAI_2'] - df_scored[col]
        stai2_reversed.append(col)
        reverse_log.append(col)
print(f"STAI Trait: Reversed {len(stai2_reversed)} items")

print(f"\nTotal items reverse-scored: {len(reverse_log)}")
print("\n✓ After reverse scoring: HIGHER values = MORE SEVERE symptoms")

AMI: Reversed 18 items
STAI State: Reversed 10 items
STAI Trait: Reversed 9 items

Total items reverse-scored: 37

✓ After reverse scoring: HIGHER values = MORE SEVERE symptoms

In [20]:
df_scored.head()

,participantID,AMI_item_0,AMI_item_1,AMI_item_2,AMI_item_3,AMI_item_4,AMI_item_5,AMI_item_6,AMI_item_7,AMI_item_8,...,STAI_2_item_10,STAI_2_item_11,STAI_2_item_12,STAI_2_item_13,STAI_2_item_14,STAI_2_item_15,STAI_2_item_16,STAI_2_item_17,STAI_2_item_18,STAI_2_item_19
0,54f4e2d1fdf99b4e913fdf01,0,4,4,3,4,0,0,4,4,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0
1,55b2d3f2fdf99b525bc839aa,1,3,3,3,2,1,0,2,1,...,0.0,0.0,1.0,3.0,0.0,1.0,0.0,2.0,1.0,0.0
2,55b3120cfdf99b6ef6263a71,1,1,1,1,1,3,1,0,1,...,0.0,1.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,2.0
4,55d4c46f58c35800113dc131,2,3,1,1,0,4,0,0,3,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
5,56b10faa6399f90011da710d,4,2,2,2,0,3,0,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
# Extract item data
item_df = df_scored[item_cols].copy()

# Per-item missingness
item_missing = item_df.isnull().sum()
item_missing_pct = (item_missing / len(item_df)) * 100

print("Missing data per questionnaire:")
print("=" * 50)
for q in included_prefixes:
    q_prefix = q if q != 'STAI_2' else 'STAI_2'
    if q == 'STAI':
        q_cols = [c for c in item_cols if c.startswith('STAI_item_')]
    else:
        q_cols = [c for c in item_cols if c.startswith(f'{q}_')]
    if q_cols:
        q_missing = item_df[q_cols].isnull().sum().sum()
        q_total = len(item_df) * len(q_cols)
        print(f"  {q:10s}: {q_missing:5d}/{q_total:6d} ({100*q_missing/q_total:5.2f}%)")

Missing data per questionnaire:
==================================================
  AMI       :     0/  5274 ( 0.00%)
  DASS21    :     0/  6153 ( 0.00%)
  MFIS      :    21/  6153 ( 0.34%)
  OASIS     :     0/  1465 ( 0.00%)
  PHQ9      :     0/  2637 ( 0.00%)
  STAI      :     0/  5860 ( 0.00%)
  STAI_2    :    20/  5860 ( 0.34%)

In [22]:
# Per-participant missingness
participant_missing = item_df.isnull().sum(axis=1)
participant_missing_pct = participant_missing / len(item_cols)

# PRIMARY APPROACH: Listwise deletion with threshold
MISSING_THRESHOLD = 0.10

n_original = len(df_scored)
high_missing_mask = participant_missing_pct > MISSING_THRESHOLD
n_excluded = high_missing_mask.sum()

print("PRIMARY APPROACH: Listwise Deletion")
print("=" * 50)
print(f"Threshold: >{MISSING_THRESHOLD*100:.0f}% missing items per participant")
print(f"Participants excluded: {n_excluded} ({100*n_excluded/n_original:.1f}%)")

# Apply
df_clean = df_scored[~high_missing_mask].copy()
item_df_clean = df_clean[item_cols].dropna()
n_complete = len(item_df_clean)

print(f"Complete cases for EFA: {n_complete}")

PRIMARY APPROACH: Listwise Deletion
==================================================
Threshold: >10% missing items per participant
Participants excluded: 2 (0.7%)
Complete cases for EFA: 291

In [23]:
df_clean

,participantID,AMI_item_0,AMI_item_1,AMI_item_2,AMI_item_3,AMI_item_4,AMI_item_5,AMI_item_6,AMI_item_7,AMI_item_8,...,STAI_2_item_10,STAI_2_item_11,STAI_2_item_12,STAI_2_item_13,STAI_2_item_14,STAI_2_item_15,STAI_2_item_16,STAI_2_item_17,STAI_2_item_18,STAI_2_item_19
0,54f4e2d1fdf99b4e913fdf01,0,4,4,3,4,0,0,4,4,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0
1,55b2d3f2fdf99b525bc839aa,1,3,3,3,2,1,0,2,1,...,0.0,0.0,1.0,3.0,0.0,1.0,0.0,2.0,1.0,0.0
2,55b3120cfdf99b6ef6263a71,1,1,1,1,1,3,1,0,1,...,0.0,1.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,2.0
4,55d4c46f58c35800113dc131,2,3,1,1,0,4,0,0,3,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
5,56b10faa6399f90011da710d,4,2,2,2,0,3,0,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,674ba8ca5c8dd0cd9cb396e7,1,3,3,1,2,1,0,0,1,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0
334,674ddf367c114b8c9bf390ab,1,3,2,1,2,1,3,3,2,...,0.0,0.0,2.0,2.0,1.0,3.0,1.0,0.0,0.0,1.0
335,674f25861382e787ce09390f,3,2,3,4,3,3,1,3,3,...,2.0,3.0,1.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
336,674f734f941491f3c0110788,0,2,1,1,1,1,0,1,1,...,2.0,1.0,2.0,0.0,1.0,2.0,3.0,2.0,1.0,1.0
337,674f8b45cca47487900fd3ee,1,3,1,1,3,0,1,2,2,...,1.0,2.0,1.0,2.0,1.0,0.0,1.0,2.0,2.0,1.0

In [27]:
from pathlib import Path

out_dir = Path(OUTPUT_BASE_DIR) / "Stage7_cleaning"
out_dir.mkdir(parents=True, exist_ok=True)

df_clean.to_csv(
    out_dir / "psych_item_clean.csv",
    index=False
)